[package]
name = "aoc2015"
version = "0.1.0"
authors = ["Kunal Bhalla <kunalb@fb.com>"]
edition = "2018"

[[bin]]
name = "day1"

[dependencies]
lazy_static = "1.4.0"
itertools = "0.10.0"
regex = "1.5.2"
