[package]
name = "aoc2015"
version = "0.1.0"
authors = ["Kunal Bhalla <kunalb@fb.com>"]
edition = "2018"

[[bin]]
name = "day1"

[[bin]]
name = "day2"

[dependencies]
lazy_static = "1.4.0"
itertools = "0.10.0"
regex = "1.5.1"
md5 = "0.7.0"